import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = Readonly<{
  children: React.ReactNode;
}>;

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="
            mx-auto p-8 pb-20
            grid grid-rows-[20px_1fr_20px] items-center justify-items-center gap-16
            max-w-lg min-h-screen
            text-foreground bg-background font-[family-name:var(--font-geist-sans)]
          "
        >
          {children}
        </div>
      </body>
    </html>
  );
}
